name: KING FM TV Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install FFmpeg and yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3 python3-pip

          sudo curl -L \
          https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
          -o /usr/local/bin/yt-dlp

          sudo chmod a+rx /usr/local/bin/yt-dlp

          ffmpeg -version
          yt-dlp --version

      - name: Start KING FM TV Stream
        env:
          FB_LIVE_URL: ${{ secrets.FB_LIVE_URL }}
        run: |
          node stream.js
