name: 24/7 Web Page Streamer

on:
  schedule:
    # 5 மணி நேரத்திற்கு ஒருமுறை தானாகவே ரன் ஆகும்
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install FFmpeg & Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg xvfb wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Start Live Streaming
        env:
          FB_STREAM_KEY: ${{ secrets.FB_STREAM_KEY }}
        run: |
          chmod +x stream.sh
          timeout 5h ./stream.sh || true
